import type { FlyRouterRoute } from "../../pietersoudan-config";

const defaultTargetPort = 8080;
export const flyRouterHealthCheckPath = "/health";

/** Fly platform DNS for resolving `.internal` hostnames from nginx. */
const flyPlatformDns = "[fdaa::3]:53";

function escapeNginxMapKey(hostname: string): string {
  return hostname.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function upstreamBackend(route: FlyRouterRoute): string {
  const port = route.targetPort ?? defaultTargetPort;
  return `${route.targetAppName}.internal:${port}`;
}

function proxyHeaders(): string {
  return `        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;`;
}

function healthLocation(): string {
  return `    location = ${flyRouterHealthCheckPath} {
        access_log off;
        default_type text/plain;
        return 200 'ok';
    }`;
}

export function getRouterBackendHostnames(routes: readonly FlyRouterRoute[]): readonly string[] {
  return Array.from(new Set(routes.map((route) => route.targetAppName))).map(
    (appName) => `${appName}.internal`,
  );
}

export function renderFlyRouterEntrypoint(routes: readonly FlyRouterRoute[]): string {
  const hosts = getRouterBackendHostnames(routes);
  const waitLoop = hosts
    .map(
      (host) => `echo "Waiting for ${host}..."
until getent ahosts "${host}" >/dev/null 2>&1; do
  sleep 1
done`,
    )
    .join("\n\n");

  return `#!/bin/sh
set -eu

${waitLoop}

echo "Backends reachable; starting nginx."
exec nginx -g "daemon off;"
`;
}

export function renderFlyRouterNginxConf(routes: readonly FlyRouterRoute[]): string {
  const mapEntries = routes.flatMap((route) =>
    route.hostnames.map(
      (hostname) => `    '${escapeNginxMapKey(hostname)}' ${upstreamBackend(route)};`,
    ),
  );

  const routedServerNames = Array.from(new Set(routes.flatMap((route) => route.hostnames))).join(
    " ",
  );

  return `# Generated by pietersoudan-ops from pietersoudan-config.ts — do not edit by hand.
resolver ${flyPlatformDns} valid=30s ipv6=on;
resolver_timeout 5s;

map $http_host $upstream_backend {
    default "";
${mapEntries.join("\n")}
}

server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;

${healthLocation()}

    location / {
        return 404;
    }
}

server {
    listen 8080;
    listen [::]:8080;
    server_name ${routedServerNames};

${healthLocation()}

    location / {
        if ($upstream_backend = "") {
            return 404;
        }

${proxyHeaders()}
        proxy_pass http://$upstream_backend;
    }
}
`;
}
